import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { imageBase64, sport } = await req.json();
    const GOOGLE_AI_API_KEY = Deno.env.get("GOOGLE_AI_API_KEY");

    if (!GOOGLE_AI_API_KEY) {
      throw new Error("GOOGLE_AI_API_KEY is not configured");
    }

    const prompt = `You are a precise sports drill diagram renderer. Your job is to redraw the hand-drawn drill diagram from the image into a clean, minimal vector-style diagram.

━━━ STEP 1: ANALYZE THE IMAGE ━━━
Before drawing anything, carefully identify and count every element:
- Circles (○) = players. Count them. Note any numbers inside. Note exact positions.
- X marks (×) = defenders. Count them. Note exact positions.
- Triangles (△) = cones. Count them. Note exact positions.
- Solid arrows (→) = running paths. Count them. Note START point, END point, and DIRECTION precisely.
- Dashed arrows (- - →) = passes. Count them. Note direction.
- Wavy lines (~~~→) = dribble paths. Count them. Note direction.
- Double lines / bold double arrows (⚡) = shots on goal. Count them. These ALWAYS point straight up toward the goal — regardless of how they appear drawn.
- Rectangles (□) = goals or zones. Count them. Note position and size.
- Any numbers or letters. Note them and their positions.

━━━ STEP 2: REDRAW — STRICT RULES ━━━
1. Draw EXACTLY the number of elements you counted. Not one more, not one less.
2. Place every element in its EXACT relative position — same layout, same spacing.
3. Every arrow must point in the EXACT same direction as in the original.
4. DO NOT add any element not in the original drawing.
5. DO NOT remove any element from the original drawing.
6. DO NOT move, rotate, or mirror any element.
7. DO NOT add a field, pitch, court, grass, floor texture, or any background other than pure white.

━━━ COLORS — EXACT ━━━
- Canvas background: pure white #FFFFFF (nothing else, ever)
- Circles (players): white fill, coral orange #F6824D border 2px, numbers in charcoal #272B35
- X marks (defenders): coral orange #F6824D — NEVER black, NEVER charcoal. Draw them slightly smaller than player circles.
- Triangles (cones): charcoal #272B35 filled — always dark/black
- All arrows and lines: coral orange #F6824D, 2-3px stroke
- Dashed lines: coral orange #F6824D dashed
- Double lines / shot arrows (⚡ or bold double arrow): coral orange #F6824D, ALWAYS pointing straight toward the goal at the top — never sideways, never diagonal
- Rectangles (goals/zones): charcoal #272B35 outline, no fill
- All text/numbers: charcoal #272B35

━━━ GOAL ━━━
- Always include one goal rectangle (charcoal #272B35 outline, no fill) at the top-center of the canvas, even if not drawn in the original. This represents the target goal for the drill.

━━━ CANVAS & CROP ━━━
- Output a tightly cropped image — include only the drawn elements plus ~40px white margin around them.
- No empty white space beyond that margin.
- Style: flat, clean, minimal. No shadows, no gradients, no 3D effects.`;


    console.log("Calling Google AI for image redraw...");

    // Extract base64 data and mime type from data URL if needed
    let imageData = imageBase64;
    let mimeType = "image/png";
    if (imageBase64.startsWith("data:")) {
      const matches = imageBase64.match(/^data:([^;]+);base64,(.+)$/);
      if (matches) {
        mimeType = matches[1];
        imageData = matches[2];
      }
    }

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${GOOGLE_AI_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{
            parts: [
              { text: prompt },
              { inlineData: { mimeType, data: imageData } }
            ]
          }],
          generationConfig: { responseModalities: ["IMAGE", "TEXT"], temperature: 0 },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Google AI error:", response.status, errorText);
      throw new Error(`Google AI error ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    const imagePart = data.candidates?.[0]?.content?.parts?.find((p: any) => p.inlineData);

    if (!imagePart?.inlineData) {
      throw new Error("No image generated by AI");
    }

    const generatedImageUrl = `data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}`;

    console.log("Successfully generated drill diagram");

    return new Response(
      JSON.stringify({ imageUrl: generatedImageUrl }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error("Error in redraw-drill-image:", msg);
    return new Response(
      JSON.stringify({ error: msg }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
